### ISSUE TITLE
[Feature Request] Ability to add new styles in web ui

### ISSUE THREAD

**Issue by sbuldan** [Haoming02/sd-webui-easy-tag-insert#10]
Ability to add new styles in web ui would be great and make the addon much for useful

**Comment by Haoming02** [comment]
wdym

**Comment by carco5a** [comment]
I believe @sbuldan means the ability to create/delete the .yml files and modify their contents in the extension UI within A1111. For me I'd just like a folder icon that launches a file explorer to the TAGS directory (like the "Open images output directory." button for A1111.

**Comment by sbuldan** [comment]
> I believe @sbuldan means the ability to create/delete the .yml files and modify their contents in the extension UI within A1111. For me I'd just like a folder icon that launches a file explorer to the TAGS directory (like the "Open images output directory." button for A1111.

Definitely

**Comment by Haoming02** [comment]
Please give the new branch a try~

**Comment by Terroosh** [comment]
> Please give the new branch a try~

Gives two errors if the controlnet extension is enabled, with controlnet disabled it runs. Loading tags works correctly.
With the Firefox browser, text you type in any row disappears the moment you press enter or click a different box. Ran Firefox in safe mode and the issue is still there. Issue does not happen in Edge.  Tags aren't saved when pressing save and an error is produced.

```
*** Error loading script: editor.py
    Traceback (most recent call last):
      File "K:\SD A1111\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "K:\SD A1111\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "K:\SD A1111\extensions\sd-webui-easy-tag-insert\scripts\editor.py", line 2, in <module>
        from scripts.utils import CARDS_FOLDER
    ImportError: cannot import name 'CARDS_FOLDER' from 'scripts.utils' (K:\SD A1111\extensions\sd-webui-controlnet\scripts\utils.py)

---
*** Error loading script: eztags.py
    Traceback (most recent call last):
      File "K:\SD A1111\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "K:\SD A1111\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "K:\SD A1111\extensions\sd-webui-easy-tag-insert\scripts\eztags.py", line 4, in <module>
        from scripts.utils import (
    ImportError: cannot import name 'SAMPLE_FOLDER' from 'scripts.utils' (K:\SD A1111\extensions\sd-webui-controlnet\scripts\utils.py)
```


```
Traceback (most recent call last):
  File "K:\SD A1111\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "K:\SD A1111\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "K:\SD A1111\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "K:\SD A1111\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "K:\SD A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "K:\SD A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "K:\SD A1111\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "K:\SD A1111\extensions\sd-webui-easy-tag-insert\scripts\editor.py", line 79, in save
    clean_empty_folders(os.path.join(CARDS_FOLDER, obj))
  File "K:\SD A1111\extensions\sd-webui-easy-tag-insert\scripts\editor.py", line 15, in clean_empty_folders
    clean_empty_folders(os.path.join(path, obj))
  File "K:\SD A1111\extensions\sd-webui-easy-tag-insert\scripts\editor.py", line 15, in clean_empty_folders
    clean_empty_folders(os.path.join(path, obj))
  File "K:\SD A1111\extensions\sd-webui-easy-tag-insert\scripts\editor.py", line 13, in clean_empty_folders
    if len(os.listdir(path)) > 0:
PermissionError: [WinError 5] Access is denied: 'K:\\$RECYCLE.BIN\\S-1-5-21-1841311846-1814077340-1092513012-1001'
```

**Comment by Haoming02** [comment]
oof, naming collision
