### ISSUE TITLE
EASY TAG randomly stoped working

### ISSUE THREAD

**Issue by Adzido** [Haoming02/sd-webui-easy-tag-insert#3]
I've had everything set up the same way for a long time and (I think) since the SD update I've had this problem: 

*** Error executing callback before_ui for C:\Users\AdziOo\stable-diffusion-webui\extensions\sd-webui-easy-tag-insert\scripts\eztags.py
    Traceback (most recent call last):
      File "C:\Users\AdziOo\stable-diffusion-webui\modules\script_callbacks.py", line 280, in before_ui_callback
        c.callback()
      File "C:\Users\AdziOo\stable-diffusion-webui\extensions\sd-webui-easy-tag-insert\scripts\eztags.py", line 113, in registerTab
        yaml_utils.reload_yaml()
      File "C:\Users\AdziOo\stable-diffusion-webui\extensions\sd-webui-easy-tag-insert\scripts\yaml_utils.py", line 41, in reload_yaml
        TAGS = merge_dictionary(TAGS, yaml.safe_load(stream))
      File "C:\Users\AdziOo\stable-diffusion-webui\venv\lib\site-packages\ruamel\yaml\main.py", line 1105, in safe_load
        error_deprecation('safe_load', 'load', arg="typ='safe', pure=True")
      File "C:\Users\AdziOo\stable-diffusion-webui\venv\lib\site-packages\ruamel\yaml\main.py", line 1039, in error_deprecation
        raise AttributeError(s, name=None)
    AttributeError:
    "safe_load()" has been removed, use

yaml = YAML(typ='safe', pure=True)
yaml.load(...)

instead of file "C:\Users\AdziOo\stable-diffusion-webui\extensions\sd-webui-easy-tag-insert\scripts\yaml_utils.py", line 41

TAGS = merge_dictionary(TAGS, yaml.safe_load(stream))

Any idea?

**Comment by Haoming02** [comment]
Please give it a try again~

**Comment by Adzido** [comment]
I did reinstalls before and it didn't help, now I did and it works.
