### ISSUE TITLE
Error appearing in A1111 UI after installing EZ Tags

### ISSUE THREAD

**Issue by MisterSeajay** [Haoming02/sd-webui-easy-tag-insert#4]
Hi, I just added this to A1111 via **Extensions > Install from URL**, I stopped A1111 totally, closed the UI, hacked together a starting YAML file and restarted and I encountered an error when opening ANY of the Extra Networks tabs:

```
Current branch is not master. Running git pull from dev.
From https://github.com/AUTOMATIC1111/stable-diffusion-webui
 * branch              dev        -> FETCH_HEAD
Already up to date.

venv "S:\GenAI\ImageGen\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0-469-gf92d6149
Commit hash: f92d61497a426a19818625c3ccdaae9beeb82b31

Launching Web UI with arguments: --data-dir=S:\GenAI\ImageGen\data --ckpt-dir=S:\GenAI\ImageGen\data\models\Checkpoints --vae-dir=S:\GenAI\ImageGen\data\models\VAE --clip-models-path=S:\GenAI\ImageGen\data\models\clip --embeddings-dir=S:\GenAI\ImageGen\data\models\embeddings --styles-file=S:\GenAI\ImageGen\data\styles*.csv --enable-insecure-extension-access --listen --no-half-vae --theme=dark --xformers

Loading weights [15012c538f] from S:\GenAI\ImageGen\data\models\Checkpoints\realisticVisionV51_v51VAE.safetensors
Creating model from config: S:\GenAI\ImageGen\stable-diffusion-webui\configs\v1-inference.yaml
Running on local URL:  http://0.0.0.0:7860

Applying attention optimization: xformers... done.
Model loaded in 6.3s (load weights from disk: 2.1s, create model: 1.2s, apply weights to model: 2.3s, move model to device: 0.1s, load textual inversion embeddings: 0.2s, calculate empty prompt: 0.2s).

To create a public link, set `share=True` in `launch()`.
Startup time: 38.0s (initial startup: 0.1s, prepare environment: 10.8s, import torch: 6.3s, import gradio: 2.1s, setup paths: 1.6s, initialize shared: 0.6s, other imports: 1.3s, setup codeformer: 0.5s, load scripts: 6.5s, create ui: 2.8s, gradio launch: 5.4s).

Traceback (most recent call last):
  File "S:\GenAI\ImageGen\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "S:\GenAI\ImageGen\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "S:\GenAI\ImageGen\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "S:\GenAI\ImageGen\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "S:\GenAI\ImageGen\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "S:\GenAI\ImageGen\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "S:\GenAI\ImageGen\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "S:\GenAI\ImageGen\stable-diffusion-webui\modules\ui_extra_networks.py", line 419, in pages_html
    return refresh()
  File "S:\GenAI\ImageGen\stable-diffusion-webui\modules\ui_extra_networks.py", line 427, in refresh
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "S:\GenAI\ImageGen\stable-diffusion-webui\modules\ui_extra_networks.py", line 427, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "S:\GenAI\ImageGen\data\extensions\sd-webui-easy-tag-insert\scripts\eztags.py", line 90, in create_html
    items_html += self.create_html_for_item(item, tabname)
  File "S:\GenAI\ImageGen\data\extensions\sd-webui-easy-tag-insert\scripts\eztags.py", line 47, in create_html_for_item
    onclick = '"' + html.escape(f"""return cardClicked({quote_js(tabname)}, {quote_js(item["prompt"].strip())}, "true")""") + '"'
AttributeError: 'dict' object has no attribute 'strip'
```

**Comment by MisterSeajay** [comment]
Oh, I think I have spotted the cause already: In my excitement I nested my tags two-deep in the yaml:
```
Pets:
  Cats:
    Garfield: A cute oversized orange tomcat with black stripes
    Nermal: A cute grey kitten
  Dogs:
    Odie: A yellow dog with long tongue
People:
  Jon: A middle aged man with short brown curly hair
```

And I think this meant that it pulled in dicts for Cats and Dogs when importing the YAML.

So maybe this is a feature request to support nested categories, a bit like you can have nested folders for LoRAs, etc.

**Comment by Haoming02** [comment]
Nested entries should work as well now~

**Comment by MisterSeajay** [comment]
Thanks. Updated & can confirm there are no errors any more.

See [Issue #5](https://github.com/Haoming02/sd-webui-easy-tag-insert/issues/5) for a follow-up request though!
